### PR TITLE
fix hattrick-youthclub player link

### PR DESCRIPTION
**Pull request by HonzaTuron**

### CODE REVIEW

**Comment by minj** [comment]
Thank you for the PR. I will double check this with HY

**Comment by minj** [comment]
@HonzaTuron  How did you come about this change?

The difference between these two URLs is that the former uses the HT youth player ID and the latter uses an internal youthclub ID, or so I have been informed.

**Comment by HonzaTuron** [comment]
@HonzaTuron The old url didn't work for me (I was logged to HY, also mentioned on conference), so I just replaced URL with HY one for player detail.

**Comment by minj** [comment]
Thanks for bringing this to our attention. The issue should be fixed on hattrick youthclub now. Let me know, if that is not the case

**Pull request closed without merging**
