### PR TITLE
HY: Switch to HTTPS

### PR DESCRIPTION
**Pull request by mackshot**
For HY we enabled https. Right now both (http and https) work. In future we will add a redirection for every request against http to https. To prepare foxtrick for that purpose we suggest to update all foxtrick-hy interaction run against https now.

Thanks for all the work you do with foxtrick!

---
This change is [Reviewable](https://reviewable.io/reviews/minj/foxtrick/1448)

### CODE REVIEW

**Comment by minj** [comment]
Would you mind rebasing it on `0.17.0` tag?

I try to do it as much as possible. This makes it easier to merge selected features to any bugfix releases.

**Comment by mackshot** [comment]
On tag 0.17.0 or tag 0.17.0.1 / branch r.0.17.0 ? I would guess that r.0.17.0 is the starting point for new releases.

**Comment by minj** [comment]
`r0.17.0` is a branch with some of those changes already merged.

`0.17.0` is the main branch point common to both `r0.17.0` and `master`. This is where 'backwards-compatible' changes go.
`0.17.0.1` is a bug fix release, one of the commits on `r0.17.0`.

I should make this clearer somehow :)

**Comment by mackshot** [comment]
This pull requests is closed an has a follow up: #1449

**Pull request closed without merging**
