### PR TITLE
HY permission workflow improvement

### PR DESCRIPTION
**Pull request by minj**
@mackshot I would like your take on this.

Currently a missing optional permission triggers the infamous plain text 401 error `youthclub.api.nopermission` that reads 'You must allow Foxtrick to access data on hattrick youthclub in the Foxtrick preferences`:

hy-before

This PR would change that into a functional preference link:

hy-after

It leads to the FT preferences page with a missing permission notification:

notification

Clicking on it **normally** leads to chrome prompt for optional permissions:

prompt

**However**, the permission was approved without the prompt on an existing install. Notice that the prompt contains domain name only. My theory is, that this is a special chrome case for protocol change. In a moment I'll test asking for this permission without user interaction.

---
This change is [Reviewable](https://reviewable.io/reviews/minj/foxtrick/1470)

### CODE REVIEW

**Comment by minj** [comment]
I was likely mistaken. I cannot reproduce it. The permission is requested after all no matter if you start the prompt manually or after user action

**Comment by mackshot** [comment]
It looks pretty nice. That should not only solve the problem with switching to https with HY it also helps out for all the users reporting 401 errors over and over again to manage it better themselves! 👍

**Comment by minj** [comment]
The orange notification has always been there, more or less. I've slightly improved it for 0.17.0, I think.

Anyway, the problem seems to be that many users have no idea how to reach 'Foxtrick preferences'

*shrugs*

**Comment by mackshot** [comment]
Yeah, thus the link to preferences is a good help!

**Comment by minj** [comment]
OK, I'll merge everything

---

Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/minj/foxtrick/1470#-:-KVq7hchmPJFYSIRIVda:bys7f7s)*

**Comment by mackshot** [comment]
Did you got any positive or negative reactions from beta-testers? I haven't seen anything on your beta forums on ht 👍

**Comment by minj** [comment]
Not really. That usually means everything's running fine :package: 

There was that hick-up with stable breaking though :wink:

**Comment by mackshot** [comment]
Yeah, loaded wrong apache configuration file :( ...
I have configured apache now that way, that all foxtrick calls are accepted on https and http, all other stuff gets redirected to https :)

**Comment by mackshot** [comment]
in the long run, http for foxtrick will be turned of as well, but then we talk about an horizon of one or two years :)

**Pull request merged**
