### PR TITLE
update vnukstats links

### PR DESCRIPTION
**Pull request by spmartin**
Links update to a new domain and routing

### CODE REVIEW

**Comment by minj** [comment]
This change is [Reviewable](https://reviewable.io/reviews/minj/foxtrick/1594)

**Comment by minj** [comment]
You might want to fix your TLS config first.

`NET::ERR_CERT_COMMON_NAME_INVALID`

**Comment by minj** [comment]
Nevermind, seems to be a cache problem

**Comment by minj** [comment]
Nope, you definitely have a problem with certificates

**Comment by spmartin** [comment]
Nope, certificate is valid until 2.12.2018. I really dont know, why you dont merge it.. old links are on OLD empty domain.

**Comment by spmartin** [comment]
Open and merge it.

**Comment by minj** [comment]
You seem to have a bit of a commanding tone. Chill.

As it says￼ "minj closed this in 28d6191 3 hours ago", it was merged with modifications.

And the reason I had to modify your changes is because your subdomain redirect to `www.` was not working properly 50:50 of tries. It would throw a certificate error instead (I assume you have two different certificates with a broken config).

Consequently, I change the URLs to include `www.`

**Comment by spmartin** [comment]
Sorry for this tone, but you denied PR for reason out of your responsibility and you tone to me as an internet boss.

Redirect works well without any complications. You had true with missing cert on a non-www domain, but on destination domain was cert fully valid.

Your comment about "merged with modifications" I dont see. Maybe I am blind or I am too used with Bitbucket :)

**Comment by minj** [comment]
Well, you submitted links without www so they *were* broken, simple as that.

Can't you open the link and see the diff for yourself?

https://github.com/minj/foxtrick/commit/28d6191b4a8e8c9daf31bafde4674a0029fe1a1b

**Comment by spmartin** [comment]
No, they didn't. If I have 301 redirect, that is not broken link.. but ok, it's already fixed for your fully satisfaction :)

I did not understood to your sentence. Its ok now.

**Comment by minj** [comment]
Listen, in all likelihood, I have been doing this longer than you, so there really is no point in talking back.

Browsers do not care about your redirects if the initial request is deemed insecure.

As to why that happened, I suspect your server has different certificates for those domains, and replied with the wrong one. Look at the error message Google Chrome gave me.

In the end, I don't really care. It was broken, I bypassed it.

**Comment by spmartin** [comment]
You are doing it more than 15 years? Ok then :)

I tested it in Opera, some special tools and Chrome (anonymous mode) and all was fine for user. I'm not saying that's you have not true, I'm just sayin' that its not problem to allow PR. Thats all mate.

Have a nic day ;)

**Pull request closed without merging**
