### PR TITLE
HY: Switch to HTTPS

### PR DESCRIPTION
**Pull request by mackshot**
Follow up to: #1448 

For HY we enabled https. Right now both (http and https) work. In future we will add a redirection for every request against http to https. To prepare foxtrick for that purpose we suggest to update all foxtrick-hy interaction run against https now.

Thanks for all the work you do with foxtrick!

---

This change is [Reviewable](https://reviewable.io/reviews/minj/foxtrick/1449)

### CODE REVIEW

**Comment by minj** [comment]
Thanks for the PR. It seems you have nailed all of those http :)

This will cause a breakage for all people, however. I need to do some testing/thinking first.

See the comments below:

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[manifest.json, line 293 at r1](https://reviewable.io:443/reviews/minj/foxtrick/1449#-KVKMhI5rnkcoC3kFHib:-KVKMhI5rnkcoC3kFHic:bdqo6pt) ([raw file](https://github.com/minj/foxtrick/blob/522332c0bf905577777dbdce2ca1e20edfc29d34/manifest.json#L293)):*
> ```JSON
> 	],
> 	"optional_permissions" : [
> 		"https://*.hattrick-youthclub.org/*",
> ```

this might cause many support requests when it stops working for all people

I need to think about how to encourage the manual intervention (i.e. users need to approve another optional permission)

---

*[content/util/cookies.js, line 23 at r1](https://reviewable.io:443/reviews/minj/foxtrick/1449#-KVKO8_-6qkvlrjhI-MS:-KVKO8_-6qkvlrjhI-MT:b-biinuv) ([raw file](https://github.com/minj/foxtrick/blob/522332c0bf905577777dbdce2ca1e20edfc29d34/content/util/cookies.js#L23)):*
> ```JavaScript
> 	const COOKIE_SPEC = {
> 		for_hty: {
> 			url: 'https://www.hattrick-youthclub.org/*',
> ```

do you want secure-only flags here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/minj/foxtrick/1449#-:-KVKOYmYKfEptS1C0NbJ:bngvu6i)*

**Comment by mackshot** [comment]
About cookies:

First: I was wondering why for "for_hty" the domain with www is used and why for "from_hty" the domain without www is used.
Second: I was not aware that you switch secure-only flag for cookie via http or https beginning. I was wondering about http in url, since I thought that for cookie definition no http or https is needed.

No, I do not want to have secure-only flag here. Am I right, that i have to switch back to http in both COOKIE_SPEC cases?

About manifest:

Yeah, I was thinking about that topic as well. I was afraid that all ft-hy interaction stopped by changing that and you seems to confirmed it. Having a way to inform the users interactive (not just in the changelog) would be pretty good. Are we able to check if the user has granted the permission to http://*.hattrick-youthclub.org and if yes ask for permission for the one with https?

**Comment by minj** [comment]
I cannot answer regarding `www` use right now. I'll need to dig deep in code (history). Catz was the one who did the initial implementation.

Secure flag is not automatic. There is no need to change anything.

We can check for permission and notify (somehow) but you need a genuine user-generated event to trigger the actual request for a new one.

**Comment by mackshot** [comment]
If secure flag is not automatic, what is the use of http vs https in url? To define a cookie the domain is needed, and not protocol as far as I know...

About the permission topic, since I have to experience with that topic, I hope you can help out there.

**Comment by minj** [comment]
I'll have to postpone further testing until Tuesday or even later.

**Comment by minj** [comment]
@mackshot cf #1470

**Comment by minj** [comment]
LGTM

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[manifest.json, line 293 at r1](https://reviewable.io:443/reviews/minj/foxtrick/1449#-KVKMhI5rnkcoC3kFHib:-KVq8le1si3zbwt6Lgcf:b-snu1np) ([raw file](https://github.com/minj/foxtrick/blob/522332c0bf905577777dbdce2ca1e20edfc29d34/manifest.json#L293)):*
<details><summary><i>Previously, minj (LA-MJ) wrote…</i></summary>
> this might cause many support requests when it stops working for all people
> 
> I need to think about how to encourage the manual intervention (i.e. users need to approve another optional permission)
</details>
Problem adressed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/minj/foxtrick/1449#-:-KVq8cXCzoByQZ8bcx5H:bb6ywmx)*

**Comment by mackshot** [comment]
Thanks for your work!

**Comment by minj** [comment]
@mackshot I'll make a beta right now just to get feedback ASAP

Since beta is built on master it's best to make a PR to master next time ;)

**Comment by minj** [comment]
I just need to tweak translations in crowdin first...

**Comment by mackshot** [comment]
Was my first pull request not to master and you asked me to make it to 0.17.0?

**Comment by minj** [comment]
It was :smile:

1) master->master
2) 0.17.0->r0.17.0
optimal) 0.17.0->master :laughing: 

It's not a big deal really, it just an easier way to work

**Comment by minj** [comment]
Again, 0.17.0 is a tag, r0.17.0 is a branch

**Comment by mackshot** [comment]
I am not sure if I got what your preferred way is:

PR based on tag 0.17.0 so you can merge them to branch r.0.17.0 and/or branch master w/o problems?

**Comment by minj** [comment]
Yep.

You start your work on tag 0.17.0, if possible. Then you merge/PR it into my master. This can reach beta quickly.

If a need to release a point release from branch r0.17.0 arises later, recursive merging into r0.17.0 as well is easy as pie since tag 0.17.0 is a direct descendant of r0.17.0. All you need to do is select the branches to merge.

This way, ideally, all commits on r0.17.0 are merge commits.

**Comment by mackshot** [comment]
Thanks for explaining your flow!

**Comment by minj** [comment]
I hope I did :laughing:

**Comment by mackshot** [comment]
I switched to foxtrick beta now too :)

That was easy, finding motivation to play HT will be harder ;)

**Comment by minj** [comment]
Finally build done. Pretending you speak 40+ languages is not easy ;)

**Comment by minj** [comment]
@mackshot I've added some github-fu to (hopefully) better explain my workflow :)

**Pull request merged**
