### PR TITLE
add-on to htms-prediction.js

### PR DESCRIPTION
**Pull request by educhielle**
I have included the add-on I mentioned in the HT forum. I called it Mimimi add-on.
It is very simple, as you can see. The comments in the code explain how it works.
Please, feel free to include it in the official version of Foxtrick, as well as, to modify the way you want to show the content.

### CODE REVIEW

**Comment by minj** [comment]
This change is [Reviewable](https://reviewable.io/reviews/minj/foxtrick/1496)

**Comment by minj** [comment]
Thanks for submitting this PR. I'll take a look at the result a bit later. Got no screenshots?

In case you plan to help out in the future, here's a page that describes using localization and setting options etc: https://github.com/minj/foxtrick/blob/master/maintainer/DevGuide.md#internationalization

Speaking of which, do you believe everyone will be happy with the result and no option to disable this is necessary?

**Comment by minj** [comment]
By the way, my first instinct says some sort of visualization would be nice. An icon, scales, gauge?

Could do something like this with the supporter repetitions result as well. The possibilities are endless, as they say. It all depends on how far you'd like to take this :wink:

**Comment by educhielle** [comment]
Hi, here it is a screenshot:
image
*my HT and foxtrick are in PT-BR.

you can see the add-on in the row after the win/draw/loss probabilities (_vitórias/empates/derrotas_)

I agree that some visualization, and also the option to enable and disable it would be nice. But first I wanted to see if you think the idea is worth of being added.

**Comment by minj** [comment]
Sure I think this would be nice to have. Especially if some visualization is added.

Not sure how you see this 'add-on name' being used though. Currently users only see module names. However, since this is attached to HTMSPrediction, I don't see this as a new module. At most it could be an option for htms. Option names are not seen by the user, however, only translated descriptions.

**Comment by educhielle** [comment]
Any idea of where to put the gauge?
1)
eb3e32e2-62a4-4c21-8754-ba1a110c5311
2)
c3411410-750d-4fda-8adf-c888cb8d4201
3)
8cd379c4-8ed1-4d5f-a502-b75a8dc731da

**Comment by minj** [comment]
I like 3) best. Any chance to modify color gradients to red - yellow - green - yellow - red?

**Comment by educhielle** [comment]
image

**Comment by minj** [comment]
OK. It might be a bit flatter (i.e. elliptic) but that's no biggie. Only the arrow is pointing wrong ;)

**Comment by educhielle** [comment]
what do you mean by pointing wrong?

**Comment by minj** [comment]
ah, nevermind. You used a different match for last screenshot :wink:

**Comment by educhielle** [comment]
I am having some trouble making the gauge flatter. I have contacted the gauge developer (https://github.com/bernii/gauge.js) to see if they can give me some help.

**Comment by educhielle** [comment]
Can we proceed with this format, at least for now, and set it as a disabled by default option of foxtrick?

**Comment by minj** [comment]
Sure. Are you not going to commit anything past the first commit?

**Comment by educhielle** [comment]
Please, look lines 127 and 182.

**Comment by minj** [comment]
Thanks for the time you put in this. I highlighted the issues I've found in the reviewable.io comments.

It would be best if you addressed them yourself if you can. However, don't hesitate to ask for clarifications or help if you have doubts how to proceed.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/minj/foxtrick/1496#-:-KdHg1LWiWxn4CSCppLh:b-iuopvc)*

**Comment by minj** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[content/matches/htms-prediction.js, line 211 at r1](https://reviewable.io:443/reviews/minj/foxtrick/1496#-KdH_qY5a5CFgqAtBEBG:-KdH_qY5a5CFgqAtBEBH:bdw1lu1) ([raw file](https://github.com/minj/foxtrick/blob/d89fac20a7c1b5136383b5197d1c64a9e3550535/content/matches/htms-prediction.js#L211)):*
> ```JavaScript
> 			var diff = acquired - expected;
> 			var luck = Math.round(100 * Math.abs(diff) * diff / 9);
> 			var luckContent = ( luck > 0 ? "+"+luck+"%" : luck+"%" );
> ```

Unfortunately this file does not follow the style guidelines. The code base is huge and cleaning it all up is a constant work in progress. 

I'll leave this task for another day :wink:

---

*[content/matches/htms-prediction.js, line 9 at r2](https://reviewable.io:443/reviews/minj/foxtrick/1496#-KdHaqylTiPMIPl5dGxM:-KdHaqylTiPMIPl5dGxN:b-3j205) ([raw file](https://github.com/minj/foxtrick/blob/1df3e0706b3409fb9fd8c9a9192ff10acd3bde27/content/matches/htms-prediction.js#L9)):*
> http://bernii.github.io/gauge.js/

This library is problematic. You would normally use the unminified version from https://github.com/bernii/gauge.js/blob/gh-pages/dist/gauge.js External libraries are stored at content/lib along with their license, which is MIT so all is well :)

However, it makes a big faux pas: it modifies `String.prototype`. It's not only a breach of etiquette (surprising properties on a built-in) but also has affect on performance.

Things like this were forbidden in AMO (Firefox add-on store). Even though this is less relevant these days due to the move to WebExtensions the underlying issues remain. We'll have to modify it.  

---

*[content/matches/htms-prediction.js, line 134 at r2](https://reviewable.io:443/reviews/minj/foxtrick/1496#-KdHe4t1MNRsyUKm04jX:-KdHe4t1MNRsyUKm04jY:b-ld4wyj) ([raw file](https://github.com/minj/foxtrick/blob/1df3e0706b3409fb9fd8c9a9192ff10acd3bde27/content/matches/htms-prediction.js#L134)):*
> ```JavaScript
> 			var mimimicanvas = cell.appendChild(doc.createElement('canvas'));
> 			mimimicanvas.id = 'ft-mimimicanvas';
> 			mimimicanvas.style.width = '80px';
> ```

we try to detach styling from scripts as much as possible

this file has a link to `resources/css/htms-statistics.css`

---

*[content/matches/htms-prediction.js, line 182 at r2](https://reviewable.io:443/reviews/minj/foxtrick/1496#-KdHdbMuVs5sYppxsmqP:-KdHdbMuVs5sYppxsmqQ:bwztr0h) ([raw file](https://github.com/minj/foxtrick/blob/1df3e0706b3409fb9fd8c9a9192ff10acd3bde27/content/matches/htms-prediction.js#L182)):*
> ```JavaScript
> 			{
> 				var b = doc.createElement('b');
> 				var luckText = 'luck'; // replace by something like Foxtrick.L10n.getString('HTMSPrediction.luck');
> ```

needs localization

---

*[content/matches/htms-prediction.js, line 183 at r2](https://reviewable.io:443/reviews/minj/foxtrick/1496#-KdHdoUoYnrAbn3m8I_j:-KdHdoUoYnrAbn3m8I_k:b-rqxx2e) ([raw file](https://github.com/minj/foxtrick/blob/1df3e0706b3409fb9fd8c9a9192ff10acd3bde27/content/matches/htms-prediction.js#L183)):*
> ```JavaScript
> 				var b = doc.createElement('b');
> 				var luckText = 'luck'; // replace by something like Foxtrick.L10n.getString('HTMSPrediction.luck');
> 				b.appendChild(doc.createTextNode(luckText));
> ```

p.s. you can just use `element.textContent = variable` in such cases

---

*[content/matches/htms-prediction.js, line 308 at r2](https://reviewable.io:443/reviews/minj/foxtrick/1496#-KdHf76Dy8gXOcw6ix4X:-KdHf76Dy8gXOcw6ix4Y:bdi1i8y) ([raw file](https://github.com/minj/foxtrick/blob/1df3e0706b3409fb9fd8c9a9192ff10acd3bde27/content/matches/htms-prediction.js#L308)):*
> ```JavaScript
> 					]
> 				};
> 				var target = document.getElementById('ft-mimimicanvas'); // your canvas element
> ```

use `doc` here. This is different in legacy Firefox code and **will not work**

We will be moving away from legacy architecture soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/minj/foxtrick/1496)*

**Pull request closed without merging**
