### PR TITLE
Luck indicator for HTMSPrediction

### PR DESCRIPTION
**Pull request by minj**

### CODE REVIEW

**Comment by minj** [comment]
This change is [Reviewable](https://reviewable.io/reviews/minj/foxtrick/1511)

**Comment by minj** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[Info.plist, line 49 at r7](https://reviewable.io:443/reviews/minj/foxtrick/1511#-Kk069eq3PHiSeel3NHW:-Kk069eq3PHiSeel3NHX:b-omy9a3) ([raw file](https://github.com/minj/foxtrick/blob/5179891f094edf2d884bb459d0096e146a9eac2b/Info.plist#L49)):*
> ```XML
> 				<string>content/lib/psico.js</string>
> 				<string>content/lib/integration.js</string>
> 				<string>content/lib/gauge.js</string>
> ```

need to move above integration and fix the modules script

---

*[content/matches/htms-prediction.js, line 125 at r7](https://reviewable.io:443/reviews/minj/foxtrick/1511#-Kk06jnyetqVCOUcUG4i:-Kk06jnyetqVCOUcUG4j:b-7j8oc4) ([raw file](https://github.com/minj/foxtrick/blob/5179891f094edf2d884bb459d0096e146a9eac2b/content/matches/htms-prediction.js#L125)):*
> ```JavaScript
> 		 * Mimimi add-on (part 1) *
> 		 **************************/
> 		var mimimiIsChecked = Foxtrick.Prefs.isModuleOptionEnabled('HTMSPrediction', 'Mimimi') && Foxtrick.Pages.Match.hasRatingsTabs(doc);
> ```

style

---

*[content/matches/htms-prediction.js, line 271 at r7](https://reviewable.io:443/reviews/minj/foxtrick/1511#-Kk0904n1HiZsdavfiO2:-Kk0904n1HiZsdavfiO3:bbvj4vq) ([raw file](https://github.com/minj/foxtrick/blob/5179891f094edf2d884bb459d0096e146a9eac2b/content/matches/htms-prediction.js#L271)):*
> ```JavaScript
> 
> 				var target = doc.getElementById('ft-mimimicanvas'); // your canvas element
> 				var gauge = new Gauge(target).setOptions(opts); // create sexy gauge!
> ```

move to `Foxtrick.*` namespace

---

*[defaults/preferences/foxtrick.js, line 195 at r7](https://reviewable.io:443/reviews/minj/foxtrick/1511#-Kk09V2XAhompb9CEP18:-Kk09V2XAhompb9CEP19:bjmw4b4) ([raw file](https://github.com/minj/foxtrick/blob/5179891f094edf2d884bb459d0096e146a9eac2b/defaults/preferences/foxtrick.js#L195)):*
> ```JavaScript
> pref("extensions.foxtrick.prefs.module.HTMSPoints.AddToPlayerList.enabled", true);
> pref("extensions.foxtrick.prefs.module.HTMSPrediction.enabled", true);
> pref("extensions.foxtrick.prefs.module.HTMSPrediction.Mimimi.enabled", false);
> ```

enable by default

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/minj/foxtrick/1511)*

**Comment by minj** [comment]
@educhielle I've tested it on some matches and I am having mixed feelings.

See this [match](https://www.hattrick.org/goto.ashx?path=/Club/Matches/Match.aspx?matchID=587295256%26SourceSystem=Hattrick%26TeamId=672194%26UpdateViewedReport=False).

It shows up as barely reaching the yellow section.

I think the problem lies in using points received as a measure, rather than the actual score. What do you think?

**Comment by minj** [comment]
it seems the visualization is incompatible with the old Firefox architecture for some reason

I cannot merge it until back-end rewrite is done.

**Comment by educhielle** [comment]
The equation to calculate the luck score is luck = Math.round(100 * Math.abs(diff) * diff / 9);
That is a quadratic equation (diff² / 3²). The idea is to bring closer to zero (green) matches with not that much randomness.

But maybe a linear approach may be better. In order to have the luck score linear to the HTMS, we need to change the equation to luck = Math.round(100 * diff / 3); That is in htms-prediction.js, line 243. Please, take a look and let me know which one do you think the user will have a better feeling about the randomness in the match.

Not working with even the newest version of Firefox?

**Comment by educhielle** [comment]
Just tested here. In the Firefox 53.0.2 it works fine.

**Pull request closed without merging**
