### PR TITLE
add new module: Haruspex

### PR DESCRIPTION
**Pull request by lucaxvi**
Alternative match prediction similar to HTMS. Preview [here](https://i.imgur.com/kxX2KLi.png?1).

### CODE REVIEW

**Comment by dominiquelee** [comment]
Hey,
Is there anything blocking this PR? I just found out about Haruspex, would love to see direct links directly from Foxtrick.
Thanks!

**Comment by minj** [comment]
Before any new features with external data sources/sinks are added, all existing features must be limited in scope, disabled by default, described and secured, as much as possible. This is needed for the new Foxtrick privacy policy, which is yet to be written.

Speaking of which, @lucaxvi should provide his own privacy/data use policy for the (meta)data that he will be receiving from this module (TCP/IP+HTTP headers and URL parameters)

**Comment by minj** [comment]
@lucaxvi still interested?

How about that policy?

**Comment by iankasab** [comment]
Is something like this good enough?

> Haruspex retains the right to log HTTP requests for internal analytics and debugging purposes.

https://haruspex.altervista.org/about

**Comment by lucaxvi** [comment]
> Haruspex retains the right to log HTTP requests for internal analytics and debugging purposes.

https://haruspex.altervista.org/about

Is something like this good enough?

**Comment by minj** [comment]
I guess so. I hope to move this forward this week unless the unexpected happens

**Comment by murko69** [comment]
Haruspex (as a standalone) isn't working. User **lucaxvi** is no more (listed as previous owner) and last login +3 weeks ago. Inactivity looks strange (since it was only 3 weeks) ut that last login is the only one I can see so....
No owner = I'm guessing no CHPP crenentials = No Haruspex?

**Comment by lucaxvi** [comment]
Yeah sorry, I closed my Hattrick team and Haruspex doesn't work anymore

**Comment by murko69** [comment]
> 
> 
> Yeah sorry, I closed my Hattrick team and Haruspex doesn't work anymore

Would you consider saving the Haruspex website by letting someone else host it and maybe apply for a new CHPP for it?
I think the CHPP might still be valid, but there's no owner atm. I'm guessing that can be solved manually though

**Pull request closed without merging**
