### PR TITLE
Updated link

### PR DESCRIPTION
**Pull request by murko69**
htarena has got a new URL and path for favicon

### CODE REVIEW

**Comment by minj** [comment]
This change is [Reviewable](https://reviewable.io/reviews/minj/foxtrick/1522)

**Comment by murko69** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/minj/foxtrick/1522)*

**Comment by murko69** [comment]
Moved to it's permanent location and I closed the previous pull.

**Comment by minj** [comment]
Strange PR. Typically people do not push merge commits from private branches in PRs :smile:

links.json changes should be applied on `cdn` branch though

**Comment by minj** [comment]
merged

**Pull request closed without merging**
