### PR TITLE
Change U20LastMatch to U21LastMatch

### PR DESCRIPTION
**Pull request by rferromoreno**
In order to support the new u21 World Cup eligibility, as requested in #1660

Sorry for the delay, I have been busy with other issues 😞. Already got calculated the days offets on my local, but I was too lazy to commit the changes and create a PR for this one.

### CODE REVIEW

**Comment by FloJ12** [comment]
Why is this not merged yet? I am also waiting for this fix

**Comment by rferromoreno** [comment]
> Why is this not merged yet? I am also waiting for this fix

It seems that @minj  has been busy lately. However, @FloJ12 , you can still download my branch and run your local build in dev mode.

**Comment by jabibi** [comment]
Hi,

Perhaps this should be changed:
```
U21LastMatch.eligibilityTitle=U20 World Cup Eligibility
U21LastMatch.eligibilityText=This player will be able to play U20 matches until:
```

**Comment by jabibi** [comment]
And this:
```
module.U21LastMatch.desc=Show the last official U20 match that a player could play in.
module.U21LastMatch.YouthPlayers.desc=Show last official U20 match in the Youth Player Details page.
module.U21LastMatch.SeniorPlayers.desc=Show last official U20 match in the Senior Player Details page.
module.U21LastMatch.AllPlayers.desc=Show last official U20 match in the Senior/Youth/NT Players page.
module.U21LastMatch.TransfersResults.desc=Show last official U20 match in the Transfers Search Results page
```

**Comment by murko69** [comment]
@jabibi
1. Those texts are all made by translators on [Crowdin](https://crowdin.com/project/foxtrick) AFAIK, so chop chop ;)  
2. I really hope that Foxtrick isn't dead but it's been since the day before Xmas 2020 since MJ commited anything to Foxtrick. I keep my fingers crossed that he has had a full plate IRL with work and life and might come back down the line......
Foxtrick desperately needs more devs.

**Comment by jabibi** [comment]
> 1. Those texts are all made by translators on [Crowdin](https://crowdin.com/project/foxtrick) AFAIK, so chop chop ;)

Original texts are made in the translation tool? I thought it was for translations

**Comment by murko69** [comment]
I ment that if you know the Master is wrong you can always translate it with correct info. English included I guess

**Comment by rferromoreno** [comment]
@jabibi has got a point. Just gimme 1-2 days and I will update those lines.

**Comment by minj** [comment]
The reason is simple as always: I find other things to do instead. Some of them may not even be super important.

Thing is, I have lost any interest for my team and the game. This does not do wonders for the motivation, as one might imagine.

Thinking about it more, I could try starting an experiment. Spending an hour per week on FT and seeing how it goes/feels. If you feel like helping, you could create issues for everything and anything that has gone wrong in my absence (seeing as that you know when I've stopped, it would be a matter of scanning the forum) and vote for things that need to be addressed first. Or even better, submit PRs for them. 

I know this is a bit rich considering that I haven't merged this for so long but oh well :shrug:

**Comment by murko69** [comment]
Glad to see you are still alive :) 
Sorry to hear about the loss of interest for the team and game though.
Sure I can try and help but actually don't understand how your 'new bug reporting' in the forum works.
This referenceID for instance?

If that's all you need you have a ton of them in the forums already from ppl reporting te same things over and over.

Since there's new rules (as you can see in this thread) U20 => U21 there are issues with XP on the performance page for certain players!
Also a lot of errors reported about the login page, that I guess have something to do with the calendar and the new NT tournaments etc
Also the new Apache League is generating errors all over the place

These three lookes like the 'hot topics' reported in the forums with various referenceID's

**Comment by minj** [comment]
@murko69 I'll see about giving you access to bug infrastructure where you can see those references

**Comment by rferromoreno** [comment]
@minj  I would like to have access to. Or try to help you. Foxtrick seems to be big enough to be mantained only by 1 person.

**Comment by minj** [comment]
Does this work as expected? I recall seeing a message somewhere that there is something wrong with this PR.

**Comment by rferromoreno** [comment]
> Does this work as expected? I recall seeing a message somewhere that there is something wrong with this PR.

You mean about the functionality or just the translations?

**Comment by minj** [comment]
Functionality. Translations are on crowdin.

**Comment by rferromoreno** [comment]
> Functionality. Translations are on crowdin.

AFAIK this was working correctly, from the last time I tested it. If you got any report on this please let me know and I can jump in and fix it.

**Comment by minj** [comment]
@murko69 the 3 issues you've mentioned should maybe be solved. I haven't actually test the actual calendar export. It is likely broken due to new matches

**Pull request merged**
