### PR TITLE
HTP modules

### PR DESCRIPTION
**Pull request by minj**
Creating a PR for HTP additions

---

This change is [Reviewable](https://reviewable.io/reviews/minj/foxtrick/1285)

### CODE REVIEW

**Comment by minj** [comment]
see [diff](http://pastebin.com/VXmYfFYN) against [content/forum/embed-media.js](../../blob/master/content/forum/embed-media.js)

suffice it to say, this is not ideal :P

**Comment by minj** [comment]
@ventouris I've moved your commits to a separate branch for now.
This type of module copying is unmaintainable. I'll try to look at it some time.

OR you could do it yourself :stuck_out_tongue:

**Comment by ventouris** [comment]
@minj  I am not sure if I understand what you want from me to do :P

**Comment by minj** [comment]
Rewrite it as an option in embed media.
Duplicating code is a no no, especially with a huge and complex module
like that.

2015-03-26 17:40 GMT+02:00, Anastasios Ventouris <notifications@github.com>:

**Comment by ventouris** [comment]
I will try to check it in the next couple of weeks. I haven't written anything with options on Foxtrick, so I need time to see how it works.

**Comment by minj** [comment]
@ventouris am I correct in assuming you are no longer interested in this?

**Comment by ventouris** [comment]
The problem is that I haven't worked with Options in Foxtrick before. So, it is somehow new to me. If I have help or guidance, I can still do it :)

**Comment by minj** [comment]
the most trivial example is [this module](/minj/foxtrick/blob/master/content/presentation/move-player-statement.js)

**Pull request closed without merging**
